#!/usr/bin/bash
# {{@@ header() @@}}
#
# Open all urls that start with "https://meet." or "https://g.co/meet/" in
# chromium.

if echo "$1" | grep -qe "^https://meet\." -e "^https://g\.co/meet/"; then
    chromium --new-window $1
else
    /usr/bin/xdg-open "$1"
fi
