#!/usr/bin/bash
# {{@@ env['dotdrop_warning'] @@}}
#
# Open all urls that start with "https://meet." in chromium

if echo "$1" | grep -q "^https://meet\."; then
    chromium --new-window $1
else
    /usr/bin/xdg-open "$1"
fi
