#!/usr/bin/bash
# {{@@ env['dotdrop_warning'] @@}}
#
# Open all urls that start with "https://meet." in chromium

if echo "$1" | grep -q "^https://meet\."; then
    raiseorlaunch -w  -c Chromium -e "chromium $1"
else
    /usr/bin/xdg-open "$1"
fi
